### ISSUE TITLE
TMG task タスクを削除する

### ISSUE THREAD

**Issue by granatetanarg** [TechTMG/TMG-ToDo#13]
`/task/delete/<id>`にPOSTしたときidのタスクを削除する

**Comment by thimi0412** [comment]
流石にDELETE文は書かなくていいと思う。`done`を`1`に更新でいいかも。
そうなると全タスク取得`/task`は`done = 1`の条件がいるな

**Comment by granatetanarg** [comment]
変更
`/task/cancel/<id>`にアクセスしたときidのタスクをキャンセル状態にする
タスク未達成 `"done" : "0"`
タスク達成 `"done" : "1"`
キャンセル `"done" : "2"`

**Comment by granatetanarg** [comment]
解決
