### ISSUE TITLE
TMG task タスクを指定して取得する

### ISSUE THREAD

**Issue by thimi0412** [TechTMG/TMG-ToDo#3]
# 実装するのも
- `/task/1`にアクセスするとidが1番目のタスクを取得する
- `/task/2`にアクセスするとidが2番目のタスクを取得する
- `/task/n`にアクセスするとidがn番目のタスクを取得する
  - n番目のタスクがなければ`そのタスクは無いよ`的なメッセージを返す

表示の際`json形式`で表示する。

**Comment by granatetanarg** [comment]
参考　アドレスから変数取得
https://qiita.com/zaburo/items/5091041a5afb2a7dffc8

**Comment by thimi0412** [comment]
pymysql
https://qiita.com/mitch0807/items/f9f6efd4e65a022a8ab9#%E3%82%AF%E3%82%A8%E3%83%AA%E3%82%92%E6%9B%B8%E3%81%84%E3%81%A6%E6%83%85%E5%A0%B1%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

**Comment by granatetanarg** [comment]
参考 取得したレコードのJSON化
https://qiita.com/nagataaaas/items/24e68a9c736aec31948e
参考 JSON文字化けの解消
https://datalove.hatenadiary.jp/entry/flask-jsonify-how-to-encode-japanese

**Comment by granatetanarg** [comment]
このissueは打ち切ります
