### ISSUE TITLE
TMG task タスクを送る

### ISSUE THREAD

**Issue by granatetanarg** [TechTMG/TMG-ToDo#5]
/postにアクセスしたら特定のJSONをPOSTする

**Comment by thimi0412** [comment]
`/task`に対してPOST送ればいいんじゃないか?

- GET `/task` タスク一覧取得
- GET `/task/<id>` idに対応したタスク取得
- POST `/task` タスクを追加
こんな感じ

**Comment by thimi0412** [comment]
https://github.com/thimi0412/ToDo/blob/e396fa14db553cbf9719f0a06f7e95458eccdd37/server.py#L67-L110

**Comment by granatetanarg** [comment]
参考　python3からMySQLにつなぐ
https://qiita.com/mitch0807/items/f9f6efd4e65a022a8ab9

参考　POSTしたJSONをpythonで使う
https://qiita.com/naoko_s/items/04d68998cfdbe9c1b5f2

**Comment by granatetanarg** [comment]
解決
